version: '3.8'
services:
  spring-boot-jpa-crud-demo:
    image: sivaprasadreddy/spring-boot-jpa-crud-demo
    container_name: spring-boot-jpa-crud-demo
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/orders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - postgresdb